# Generated by Django 4.2.5 on 2023-09-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('counter', models.PositiveIntegerField(default=0)),
                ('time_crete', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
